// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/IndigoCloud6/go-web-template/internal/config"
	"github.com/IndigoCloud6/go-web-template/internal/handler"
	"github.com/IndigoCloud6/go-web-template/internal/repository"
	"github.com/IndigoCloud6/go-web-template/internal/service"
	"github.com/IndigoCloud6/go-web-template/pkg/database"
	redis2 "github.com/IndigoCloud6/go-web-template/pkg/redis"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies
func InitializeApp(cfg *config.Config) (*handler.UserHandler, error) {
	db, err := provideDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	client, err := provideRedis(cfg)
	if err != nil {
		return nil, err
	}
	userService := service.NewUserService(userRepository, client)
	userHandler := handler.NewUserHandler(userService)
	return userHandler, nil
}

// wire.go:

func provideDatabase(cfg *config.Config) (*gorm.DB, error) {
	return database.NewMySQL(&cfg.Database)
}

func provideRedis(cfg *config.Config) (*redis.Client, error) {
	return redis2.NewRedis(&cfg.Redis)
}
